### ISSUE TITLE
plugin no longer works

### ISSUE THREAD

**Issue by elem-azar-unis** [lvarayut/github-file-icons#12]
The github page has upgraded. This plugin doesn't work now.

**Comment by lvarayut** [comment]
Thanks for reporting the issue. I'm looking into it.

**Comment by lvarayut** [comment]
The issue has been fixed in 27dbdd9965284a50a5a43889c5cef886306c4a21. I've just published a new version that is being reviewed by the Google team. It should be live soon.

**Comment by lvarayut** [comment]
It's now live 🎉
