### ISSUE TITLE
double icons with github refined plugin

### ISSUE THREAD

**Issue by muescha** [lvarayut/github-file-icons#5]
double icons with the github refined plugin ( https://github.com/sindresorhus/refined-github )

**Comment by muescha** [comment]
my screenshot: https://github.com/sindresorhus/refined-github/issues/2045

possible solution how to solve it: https://github.com/sindresorhus/refined-github/issues/1993#issuecomment-487423210

**Comment by bfred-it** [comment]
This extension adds the icon as `:before` and that solution won't work. I just fixed compatibility with this one though: https://github.com/xxhomey19/github-file-icon

**Comment by muescha** [comment]
yes the xxhomey19 plugin works - thx

**Comment by lvarayut** [comment]
Thanks for reporting the issue. I'll disable the "edit files faster" feature from refined-github for now. PR is welcome
